import LatestBoards from './components/LatestBoards';

export const dynamic='force-dynamic';
const buyItems=[['PC','폐컴퓨터 · 중고컴퓨터','데스크탑, 노트북, 모니터, 일체형 PC, 사무용 PC와 PC방 장비까지 상태와 수량을 확인해 매입합니다.','컴퓨터 매입 · 폐컴퓨터 수거'],['SV','서버 · 전산장비','랙서버, 워크스테이션, 스토리지, UPS 등 기업 전산실에서 발생하는 장비를 일괄 상담합니다.','서버 매입 · 전산장비 매입'],['NW','네트워크 · 통신장비','스위치, 라우터, 통신장비, 보드류, 케이블 및 각종 기업 불용 전산자재를 확인합니다.','네트워크 · 통신장비 매입'],['HD','저장장치 · 부품','CPU, RAM, SSD, HDD, 그래픽카드 등 부품과 저장장치도 장비와 함께 매입 상담이 가능합니다.','컴퓨터 부품 · HDD · SSD']];
const trust=[['전국','출장·택배 매입 상담'],['기업·기관','대량 IT자산 일괄 처리'],['보안','HDD·SSD 데이터 처리'],['원스톱','견적부터 수거·정산까지']];
const customers=[['기업 · 사무실','PC 교체·이전·폐업으로 발생한 컴퓨터와 전산장비'],['관공서 · 학교 · 병원','불용 전산장비와 저장장치 보안 처리가 필요한 현장'],['PC방 · 사업장','PC·모니터·부품 등 여러 품목의 대량 일괄 매입'],['개인 · 소량','컴퓨터 한두 대와 부품의 택배·방문 매입 상담']];
const process=[['01','사진·정보 접수','품목, 수량, 모델명과 사진을 보내주시면 상담을 시작합니다.'],['02','견적 확인','사양·상태·수량과 현장 조건을 기준으로 매입 조건을 안내합니다.'],['03','출장·택배 수거','대량 물량은 방문, 소량은 택배 등 상황에 맞춰 진행합니다.'],['04','검수·정산','현장 또는 입고 검수 후 확인된 조건에 따라 매입을 마무리합니다.']];
export default function Home(){return <main className="homeV3">
<header className="siteHeader"><div className="container navWrap"><a href="#top" className="brand"><span className="brandMark">O</span><span>올바른<span className="brandBlue">매입</span></span></a><nav className="desktopNav"><a href="#items">매입품목</a><a href="#business">기업·대량매입</a><a href="#security">데이터보안</a><a href="#process">매입절차</a><a href="/customer/notice">고객센터</a></nav><a href="/request/visit" className="btn btnPrimary smallBtn">견적 문의</a></div></header>
<section id="top" className="premiumHero"><div className="container premiumHeroGrid"><div className="premiumCopy"><div className="verifiedLabel"><span>✓</span> 전국 폐컴퓨터 · IT자산 전문 매입</div><h1>기업 전산장비부터<br/><em>폐·중고 컴퓨터까지</em><br/>한 번에 매입합니다.</h1><p>올바른매입은 컴퓨터 한 대부터 기업 전산실의 서버·네트워크 장비와 불용 IT자산까지 품목과 수량에 맞춰 상담합니다. 대량 물량은 출장 수거, 저장장치는 데이터 보안 처리까지 함께 진행할 수 있습니다.</p><div className="premiumActions"><a href="/request/visit" className="btn premiumPrimary">사진으로 빠른 견적 <b>→</b></a><a href="/request/pickup" className="btn premiumSecondary">수거 신청</a></div><div className="miniTrust"><span>기업·관공서·학교·병원</span><i/><span>전국 상담</span><i/><span>대량 수거</span></div></div><div className="assetCard"><div className="assetTop"><span>OLBARUN BUY</span><b>IT ASSET MANAGEMENT</b></div><div className="assetTitle"><small>전산장비 매입 범위</small><strong>PC · SERVER · NETWORK</strong></div><div className="assetVisual"><div className="rack"><span/><span/><span/><span/><span/></div><div className="screen"><b>IT</b></div><div className="tower">PC</div></div><div className="assetFoot"><div><small>기업 대량 물량</small><b>출장 견적 · 일괄 수거</b></div><div><small>저장장치</small><b>데이터 삭제 · 물리 파기</b></div></div></div></div></section>
<section className="trustBar"><div className="container trustBarGrid">{trust.map(([a,b],i)=><div key={a}><span>0{i+1}</span><strong>{a}</strong><p>{b}</p></div>)}</div></section>
<section id="items" className="section premiumSection"><div className="container"><div className="premiumHead"><div><span>WHAT WE BUY</span><h2>매입 가능한 주요 품목</h2></div><p>여러 종류의 장비가 섞여 있어도 괜찮습니다.<br/>폐기하기 전에 매입 가능 여부부터 확인해 보세요.</p></div><div className="premiumItems">{buyItems.map(([icon,title,desc,key],i)=><article key={title}><div className="itemTop"><span className="itemIcon">{icon}</span><b>0{i+1}</b></div><h3>{title}</h3><p>{desc}</p><small>{key}</small><a href="/request/visit">견적 문의하기 <b>↗</b></a></article>)}</div></div></section>
<section id="business" className="enterprise"><div className="container enterpriseGrid"><div><span className="darkLabel">FOR BUSINESS</span><h2>기업 불용 IT자산,<br/><em>처리는 더 체계적으로.</em></h2><p className="enterpriseLead">장비 교체나 사무실 이전 때 발생하는 수십·수백 대의 컴퓨터와 서버. 품목별로 업체를 찾지 않고 올바른매입에서 한 번에 상담하세요.</p><div className="enterpriseChecks"><span>✓ 현장 방문견적 상담</span><span>✓ 컴퓨터·서버·네트워크 일괄 수거</span><span>✓ HDD·SSD 보안 처리 상담</span><span>✓ 기업·기관 대량 물량 대응</span></div><a href="/request/visit" className="btn enterpriseBtn">기업 대량견적 문의 →</a></div><div className="clientMatrix">{customers.map(([t,d],i)=><article key={t}><b>0{i+1}</b><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section id="security" className="section securePremium"><div className="container"><div className="premiumHead"><div><span>DATA SECURITY</span><h2>수거보다 먼저 생각해야 할<br/>데이터 보안</h2></div><p>매입되는 장비에 개인정보나 기업 자료가 남아 있다면<br/>저장장치 처리 방식까지 함께 확인해야 합니다.</p></div><div className="secureGrid"><article><div className="securePhoto hddBefore"><span>HDD</span></div><b>STEP 01</b><h3>저장장치 확인</h3><p>수거 장비에서 HDD·SSD 등 저장장치를 확인하고 보안 처리 대상을 구분합니다.</p></article><article><div className="securePhoto hddPunch"><span>●</span></div><b>STEP 02</b><h3>삭제 또는 물리적 천공</h3><p>요청 조건에 따라 데이터 삭제 또는 물리적 천공 등 적합한 방식을 안내합니다.</p></article><article><div className="securePhoto hddDone"><span>×</span></div><b>STEP 03</b><h3>파기 대상 후속 처리</h3><p>재사용 장비와 파기 대상을 구분해 안전한 후속 처리 절차를 진행합니다.</p></article></div><div className="securityNote"><strong>기업 데이터 보안이 걱정되시나요?</strong><span>견적 요청 시 저장장치 종류와 원하는 처리 방법을 함께 알려주세요.</span><a href="/request/visit">보안 파기 포함 견적 →</a></div></div></section>
<section id="process" className="section premiumProcess"><div className="container"><div className="premiumHead"><div><span>PROCESS</span><h2>문의부터 정산까지<br/>4단계로 간단하게</h2></div><p>처음 문의하시는 분도 쉽게 진행할 수 있도록<br/>필요한 정보와 다음 단계를 명확하게 안내합니다.</p></div><div className="premiumProcessGrid">{process.map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div><div className="centerActions"><a href="/request/visit" className="btn btnPrimary">방문견적 의뢰</a><a href="/request/pickup" className="btn btnGhost">수거 신청서</a><a href="/process" className="simpleLink">매입절차 자세히 보기 →</a></div></div></section>
<section className="keywordSection"><div className="container keywordGrid"><div><span>OLBARUN BUY</span><h2>폐컴퓨터 매입부터<br/>서버·전산장비 전국매입까지</h2></div><div><p><strong>올바른매입</strong>은 폐컴퓨터·중고컴퓨터 매입, 폐컴퓨터 수거, 서버 매입, 전산장비 매입을 함께 진행합니다. 데스크탑·노트북·모니터부터 서버·워크스테이션·네트워크 장비·통신장비와 기업 불용 IT자산까지 상담할 수 있습니다.</p><p>기업·관공서·학교·병원·사무실의 대량 컴퓨터와 전산장비는 현장 조건과 수량을 확인해 출장 수거를 상담하며, HDD·SSD 등 저장장치의 데이터 삭제와 물리적 파기가 필요한 경우 보안 처리도 함께 문의할 수 있습니다.</p></div></div></section>
<section className="premiumCta"><div className="container premiumCtaInner"><div><span>빠른 매입 상담</span><h2>처분할 장비 사진만 준비하세요.<br/>나머지는 올바른매입이 안내합니다.</h2></div><div><a href="/request/visit" className="btn ctaWhite">무료 견적 신청 →</a><a href="/customer/qna">먼저 문의하기</a></div></div></section>
<LatestBoards/>
<footer className="footer"><div className="container footerGrid"><div className="brand footerBrand"><span className="brandMark">O</span><span>올바른매입</span></div><div><strong>매입 서비스</strong><p>폐·중고컴퓨터<br/>서버 · 전산장비<br/>네트워크 · 통신장비</p></div><div><strong>신청·문의</strong><p><a href="/request/pickup">수거신청서</a><br/><a href="/request/visit">방문견적 의뢰서</a><br/><a href="/customer/qna">1:1 문의</a></p></div><div><strong>데이터 보안</strong><p>HDD · SSD 데이터 삭제 및 물리적 파기 상담</p></div></div></footer>
<aside className="quickSide" aria-label="빠른 메뉴"><a className="quickSideMain" href="/request/visit"><span>▤</span><strong>최저가 견적<br/>무료신청</strong></a><a href="/customer/qna"><span>☎</span><strong>상담문의</strong></a><a href="#process"><span>⚒</span><strong>매입절차</strong></a><a href="/request/pickup"><span>▣</span><strong>수거신청</strong></a><a href="#security"><span>◉</span><strong>데이터파기</strong></a></aside>
<div className="mobileBottom"><a href="/request/pickup"><b>⌂</b><span>수거신청</span></a><a href="/request/visit" className="primary"><b>＋</b><span>빠른견적</span></a><a href="/customer/qna"><b>Q</b><span>1:1문의</span></a></div>
</main>}
