import MobileMenu from './components/MobileMenu';
import './home-v4.css';

const services=[
 {cls:'ship',icon:'📦',title:'택배 & 화물 매입신청',desc:'소량도 OK! 전국 택배·화물로 간편하게',href:'/request',image:'/images/home/service-delivery.webp'},
 {cls:'visit',icon:'🚚',title:'출장 매입 신청',desc:'부산·경남 지역 전문 기사 출장 방문 수거',href:'/request/visit',image:'/images/home/service-visit.webp'},
 {cls:'free',icon:'♻️',title:'무상 수거 신청',desc:'재사용 가능한 PC·모니터 등 무상 수거 상담',href:'/request/free',image:'/images/home/service-free.webp'},
 {cls:'qna',icon:'💬',title:'1:1 문의 게시판',desc:'궁금한 사항을 빠르게 상담해드립니다.',href:'/customer/qna',image:'/images/home/service-qna.webp'},
];
const strengths=[['📍','부산·경남','전문 출장매입','부산·경남 전 지역 신속한 출장 상담'],['📦','전국','택배 매입 상담','소량도 가능한 안전한 택배 매입'],['🛡️','보안','데이터 파기','HDD/SSD 보안 파기·천공 처리'],['⚙️','원스톱','수거 서비스','상담 → 수거 → 검수 → 입금 한 번에 진행']];
export default function Home(){return <main className="homeV4"><header className="homeHeader"><div className="container homeNav"><a href="/" className="homeLogo"><img src="/images/logo/올바른로고.png" alt="올바른매입"/></a><nav><a href="#about">회사소개</a><a href="/process">매입안내</a><a href="#services">매입품목</a><a href="/buy/busan">지역안내</a><a href="/customer/notice">고객센터</a></nav><a className="homePhone" href="tel:01066484886"><span>☎</span><small>상담문의<strong>010-6648-4886</strong></small></a><MobileMenu/></div></header>
<section className="homeHero" id="about"><div className="container homeHeroGrid"><div className="homeHeroCopy"><div className="homeBadge">✓ 부산·경남 폐컴퓨터 · IT자산 출장매입</div><h1>기업 전산장비부터<br/><em>폐·중고 컴퓨터까지</em><br/>한 번에 매입합니다.</h1><p>부산에 기반을 둔 올바른매입은 부산·경남 지역의 컴퓨터 한 대부터 기업 전산실 서버·네트워크 장비와 불용 IT자산까지 출장 상담합니다. 타 지역은 품목과 수량에 따라 택배 매입을 상담하며 저장장치 데이터 보안 처리도 함께 진행할 수 있습니다.</p></div><div className="homeHeroVisual"><img src="/images/home/hero-it-buy.webp" alt="올바른매입 폐컴퓨터 서버 전산장비 출장매입"/><div className="heroTrust"><span>♻️<b>친환경<br/>자원순환</b></span><span>🛡️<b>데이터보안<br/>안전처리</b></span><span>🏢<b>기업·관공서<br/>전문매입</b></span></div></div><div className="heroActions"><a className="heroQuote" href="/request/visit"><span>▤</span><strong>사진으로 빠른 견적<small>사진만 보내도 빠른 견적!</small></strong><b>›</b></a><a className="heroPickup" href="/request"><span>🚚</span><strong>수거 신청<small>출장·방문·택배 선택 가능</small></strong><b>›</b></a></div><div className="heroMini"><span>✓ 부산·경남 출장</span><span>✓ 전국 택배 상담</span><span>✓ 기업 대량 수거</span><span>✓ 데이터 보안 처리</span></div></div></section>
<section className="homeServices" id="services"><div className="container serviceGridV4">{services.map(s=><a href={s.href} className={`serviceCardV4 ${s.cls}`} key={s.title}><div><span className="serviceIcon">{s.icon}</span><h2>{s.title}</h2><p>{s.desc}</p><i>→</i></div><img src={s.image} alt={s.title}/></a>)}</div></section>
<section className="homeStrength"><div className="container strengthGrid">{strengths.map(([icon,k,t,d],i)=><article key={k}><small>0{i+1}</small><span>{icon}</span><div><b>{k}</b><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
<section className="homeBottom"><div className="container"><div><small>지금 바로 상담하세요!</small><a href="tel:01066484886">☎ <strong>010-6648-4886</strong></a></div><div><strong>폐컴퓨터 · 서버장비 · 네트워크장비 · IT자산 매입 전문</strong><p>부산·경남 지역 빠른 출장 상담! 전국 택배도 가능합니다.</p></div></div></section></main>}
