import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

type AreaData={
 name:string; neighborhoods:string[]; focus:string; intro:string; cases:[string,string][]; faq:[string,string][]; nearby:string[];
};

const busanData:Record<string,AreaData>={
 'jung-gu':{name:'중구',neighborhoods:['중앙동','남포동','광복동','대청동','보수동','부평동','동광동','영주동'],focus:'남포·중앙동 상가와 사무실 중심 출장매입',intro:'중구는 남포동·광복동 상권과 중앙동 업무지역, 부산항 인근 사무실과 숙박·유통업 사업장이 함께 분포합니다. 매장 정리나 사무실 이전 과정에서 발생하는 업무용 PC, POS 장비, 모니터, 네트워크 장비를 묶어 상담할 수 있습니다.',cases:[['남포·광복 상가 장비 정리','매장 폐업이나 리뉴얼 때 나오는 카운터 PC, POS, 모니터, 공유기와 주변장비를 품목별로 확인합니다.'],['중앙동 사무실 이전','업무용 데스크탑과 노트북, 문서용 PC, NAS·스위치 등 사무실 전산장비를 한 번에 견적합니다.'],['숙박·서비스업 불용장비','프런트 PC, 객실 운영용 장비, CCTV 저장장치와 네트워크 장비가 함께 나오는 경우 일괄 상담합니다.'],['항만·유통업 전산장비','물류·유통 사무실의 PC와 서버, 통신장비, 케이블류 등 불용 전산자재까지 확인합니다.']],faq:[['남포동 매장에서 쓰던 컴퓨터도 매입하나요?','매장 운영용 PC, 모니터, POS 연동 장비 등 품목을 확인해 상담합니다.'],['중앙동 사무실 PC가 여러 대인데 출장 가능한가요?','수량과 장비 종류를 먼저 확인한 뒤 방문 일정과 수거 방법을 협의합니다.'],['HDD에 고객정보가 남아 있어도 되나요?','요청 시 저장장치 분리와 물리적 천공 파기 상담이 가능합니다.'],['서버와 네트워크 장비도 같이 처리할 수 있나요?','랙서버, NAS, 스위치, 라우터, UPS 등도 함께 상담할 수 있습니다.']],nearby:['seo-gu','dong-gu','yeongdo-gu']},
 'seo-gu':{name:'서구',neighborhoods:['동대신동','서대신동','부민동','아미동','초장동','충무동','남부민동','암남동'],focus:'병원·의료시설·대학·사무실 전산장비 매입',intro:'서구는 의료기관과 대학, 주거지역과 전통상권이 함께 있는 지역입니다. 병원·의원에서 교체되는 업무용 PC와 모니터, 대학·연구시설의 전산장비, 사무실 이전으로 발생하는 불용 PC를 수량에 맞춰 출장 상담합니다.',cases:[['병원·의원 전산장비 교체','접수·원무용 PC, 진료실 컴퓨터, 모니터와 네트워크 장비를 분리해 확인합니다.'],['대학·연구시설 불용 PC','교육·연구용 데스크탑, 워크스테이션, 서버와 주변기기를 일괄 견적합니다.'],['대신동 사무실 이전','사무용 PC와 복수의 모니터, 노트북, NAS 등 업무장비를 일정에 맞춰 수거 상담합니다.'],['남부민·암남 사업장','업무용 컴퓨터와 통신장비, 케이블·보드류 등 혼합 불용자재도 품목별로 분류합니다.']],faq:[['병원에서 사용하던 PC도 매입 가능한가요?','사양과 상태, 수량을 확인해 상담할 수 있으며 저장장치 보안처리도 함께 협의할 수 있습니다.'],['대학 연구실 워크스테이션도 가능한가요?','워크스테이션과 서버, 네트워크 장비도 함께 확인합니다.'],['개인정보가 있는 HDD는 어떻게 하나요?','요청 시 물리적 천공 파기 방식으로 처리 상담이 가능합니다.']],nearby:['jung-gu','saha-gu','busanjin-gu']},
 'dong-gu':{name:'동구',neighborhoods:['초량동','수정동','좌천동','범일동'],focus:'부산역·범일동 업무시설과 숙박·유통업 출장매입',intro:'동구는 부산역 주변 숙박·업무시설과 범일동 유통·상업지역이 공존합니다. 사무실 이전, 숙박업 리뉴얼, 매장 정리 과정에서 나오는 폐컴퓨터와 모니터, 서버·네트워크 장비를 현장 상황에 맞춰 매입 상담합니다.',cases:[['부산역 인근 숙박업 장비','프런트 PC, 관리용 컴퓨터, 공유기·스위치 등 운영장비를 묶어 확인합니다.'],['초량 사무실 이전','사무용 데스크탑과 모니터, 노트북, NAS를 일정에 맞춰 방문 상담합니다.'],['범일동 상가·유통업','매장 PC, POS 연동장비, 사무실 컴퓨터와 통신자재를 함께 정리할 수 있습니다.'],['기업 불용 서버','랙서버, 워크스테이션, 스위치, UPS 등 전산실 장비도 품목별로 견적합니다.']],faq:[['부산역 근처 사무실도 방문 가능한가요?','동구 전 지역 출장매입 상담이 가능합니다.'],['숙박업소 PC와 네트워크 장비를 함께 처리할 수 있나요?','PC와 모니터, 네트워크 장비를 한 번에 확인할 수 있습니다.'],['HDD 파기도 가능한가요?','요청 시 저장장치 천공 파기 상담이 가능합니다.']],nearby:['jung-gu','busanjin-gu','nam-gu']},
 'yeongdo-gu':{name:'영도구',neighborhoods:['남항동','영선동','신선동','봉래동','청학동','동삼동'],focus:'조선·해양·공장·사업장 불용 전산장비 매입',intro:'영도구는 조선·해양 관련 사업장과 공장, 창고, 사무시설이 함께 분포합니다. 현장에서 사용하던 업무용 PC뿐 아니라 산업용 컴퓨터, 서버, 네트워크 장비와 각종 전산 불용자재까지 수량에 맞춰 출장 상담합니다.',cases:[['조선·해양 사업장 PC','현장사무실과 관리부서에서 사용한 데스크탑, 모니터, 노트북을 분류해 확인합니다.'],['공장·창고 전산장비','생산관리용 PC, 네트워크 장비, 통신장비와 UPS 등 혼합 장비를 함께 상담합니다.'],['동삼동 기관·연구시설','업무용 PC와 서버, 워크스테이션, 저장장치 등 전산장비 교체 물량을 견적합니다.'],['대량 불용자재 수거','장비 수량이 많은 경우 현장 동선과 적재 여건을 확인해 방문 일정을 협의합니다.']],faq:[['공장에 있는 오래된 컴퓨터도 매입하나요?','사양과 상태에 따라 매입 또는 수거 방법을 안내합니다.'],['산업용 PC와 서버를 같이 볼 수 있나요?','가능합니다. 장비 모델과 수량을 먼저 확인하면 보다 정확한 상담이 가능합니다.'],['현장에서 HDD 파기 상담도 되나요?','요청 시 저장장치 분리 및 천공 처리 방법을 협의할 수 있습니다.']],nearby:['jung-gu','nam-gu','saha-gu']},
 'dongnae-gu':{name:'동래구',neighborhoods:['명륜동','온천동','사직동','수안동','복천동','낙민동','안락동','명장동'],focus:'병원·학원·사무실 중심 폐컴퓨터 출장매입',intro:'동래구는 병원·의원과 학원, 사무실, 상가가 밀집한 생활권입니다. 데스크탑과 모니터 교체, 학원 이전, 병원 전산장비 교체 등에서 발생하는 폐PC와 네트워크 장비를 지역별 일정에 맞춰 상담합니다.',cases:[['병원·의원 PC 교체','접수·원무·진료실 PC와 모니터, 네트워크 장비를 함께 확인합니다.'],['사직·명륜 학원 장비','교육용 컴퓨터, 노트북, 모니터와 공유기·스위치 등을 일괄 견적합니다.'],['온천동 사무실 이전','업무용 PC와 NAS, 프린터 주변 전산장비의 수거 일정을 조율합니다.'],['안락·명장 사업장','소규모 사업장의 PC와 불용 전산자재를 품목별로 상담합니다.']],faq:[['학원 컴퓨터가 10대 정도인데 출장 가능한가요?','품목과 위치를 확인한 뒤 출장 또는 택배매입 중 적합한 방법을 안내합니다.'],['병원 HDD도 천공 가능한가요?','개인정보 보호가 필요한 저장장치는 요청 시 물리적 파기 상담이 가능합니다.'],['모니터도 같이 매입하나요?','크기와 상태를 확인해 PC와 함께 견적할 수 있습니다.']],nearby:['yeonje-gu','geumjeong-gu','haeundae-gu','busanjin-gu']},
 'nam-gu':{name:'남구',neighborhoods:['대연동','용호동','용당동','감만동','우암동','문현동'],focus:'대학·오피스·항만 인접 사업장 전산장비 매입',intro:'남구는 대학가와 대연동 상권, 문현 업무지역, 감만·용당 일대 사업장이 함께 형성돼 있습니다. 학교·사무실·사업장의 폐컴퓨터와 서버, 네트워크 장비를 수량과 현장 여건에 맞춰 출장매입합니다.',cases:[['대학·교육시설 PC','강의실·연구실·행정실에서 교체되는 데스크탑과 모니터, 워크스테이션을 확인합니다.'],['문현 업무지구 사무실','사무용 PC, 노트북, NAS와 네트워크 장비를 이전 일정에 맞춰 상담합니다.'],['감만·용당 사업장','물류·사업장 관리용 PC와 통신장비, UPS 등 전산장비를 일괄 견적합니다.'],['대연·용호 상가','매장 PC와 모니터, POS 주변 전산장비도 함께 확인합니다.']],faq:[['대학 연구실 장비도 매입하나요?','PC, 워크스테이션, 서버 등 장비 종류와 사양을 확인해 상담합니다.'],['문현동 사무실 대량 장비도 방문 가능한가요?','수량이 많은 경우 사전 사진이나 목록을 받은 뒤 현장 방문을 협의합니다.'],['저장장치 보안처리는 어떻게 하나요?','요청 시 HDD 분리와 천공 파기 방식 상담이 가능합니다.']],nearby:['busanjin-gu','suyeong-gu','dong-gu','yeongdo-gu']},
 'buk-gu':{name:'북구',neighborhoods:['구포동','덕천동','만덕동','금곡동','화명동'],focus:'상가·학원·사무실·소규모 사업장 출장매입',intro:'북구는 덕천·화명 상권과 학원가, 구포 일대 사무실과 소규모 사업장이 고르게 분포합니다. 업무용 PC와 학원 컴퓨터, 매장 장비 교체 시 발생하는 폐컴퓨터를 수량에 따라 출장 또는 택배 방식으로 상담합니다.',cases:[['덕천 상가·사무실','매장 PC와 사무용 데스크탑, 모니터를 함께 확인합니다.'],['화명 학원·교육시설','교육용 PC, 노트북, 모니터와 네트워크 장비를 일괄 견적합니다.'],['구포 사업장 장비','업무용 PC와 NAS, 스위치, 통신장비 등을 품목별로 상담합니다.'],['만덕·금곡 소량 장비','소량은 품목에 따라 택배매입 또는 방문 가능 여부를 안내합니다.']],faq:[['북구 전 지역 출장 가능한가요?','장비 수량과 품목을 확인한 뒤 방문 일정을 협의합니다.'],['학원 컴퓨터와 모니터를 같이 견적할 수 있나요?','가능합니다. 장비 사양과 상태를 함께 확인합니다.'],['소량이면 택배도 가능한가요?','출장 효율이 낮은 소량 품목은 택배매입을 안내할 수 있습니다.']],nearby:['sasang-gu','geumjeong-gu','dongnae-gu']},
 'haeundae-gu':{name:'해운대구',neighborhoods:['우동','중동','좌동','재송동','반여동','반송동','송정동'],focus:'센텀 기업·IT·병원·숙박업 전산장비 매입',intro:'해운대구는 센텀시티의 기업·IT 업무시설과 병원, 호텔·숙박업, 대형 상권이 함께 발달한 지역입니다. 기업 PC 교체부터 서버·네트워크 장비, 숙박업 운영 PC와 불용 전산장비까지 출장매입을 상담합니다.',cases:[['센텀 기업 전산장비','사무용 PC, 노트북, 워크스테이션, 서버와 네트워크 스위치를 일괄 확인합니다.'],['병원·의료시설 장비','원무·진료실 PC와 모니터, NAS 등 개인정보 관리가 필요한 장비를 상담합니다.'],['호텔·숙박업 운영장비','프런트 PC, 관리용 컴퓨터와 네트워크 장비를 함께 견적합니다.'],['재송·반여 사업장','사업장 이전이나 장비교체로 발생한 PC와 통신장비, 불용자재를 분류합니다.']],faq:[['센텀 기업 PC가 수십 대인데 방문 가능한가요?','대량 장비는 사전 목록이나 사진을 확인한 뒤 방문견적 일정을 협의합니다.'],['서버랙 장비도 매입하나요?','랙서버, 스위치, UPS 등 전산실 장비도 함께 상담합니다.'],['기업 HDD는 별도로 파기할 수 있나요?','요청 시 저장장치 분리와 물리적 천공 파기 상담이 가능합니다.']],nearby:['suyeong-gu','dongnae-gu','gijang-gun','yeonje-gu']},
 'saha-gu':{name:'사하구',neighborhoods:['괴정동','당리동','하단동','신평동','장림동','다대동','구평동','감천동'],focus:'산업시설·공장·사업장 대량 불용 전산장비 매입',intro:'사하구는 신평·장림 산업지역과 하단 상권, 다대·구평 사업장이 함께 분포합니다. 공장 사무실과 생산관리 공간에서 사용한 PC, 서버, 네트워크 장비, 통신자재를 수량과 현장 여건에 맞춰 출장매입합니다.',cases:[['신평·장림 공장 PC','생산관리·사무용 데스크탑과 모니터, 네트워크 장비를 현장별로 분류합니다.'],['하단 사무실·상가','업무용 PC와 노트북, 매장 컴퓨터, 공유기 등을 일괄 견적합니다.'],['다대·구평 사업장','공장·물류사업장의 서버, UPS, 통신장비와 불용 전산자재를 함께 상담합니다.'],['폐업·이전 대량수거','장비량이 많은 경우 적재 공간과 반출 동선을 먼저 확인해 수거 일정을 조율합니다.']],faq:[['공장에 있는 PC와 네트워크 장비를 한꺼번에 매입하나요?','가능합니다. 장비 목록이나 사진을 보내주시면 사전 상담에 도움이 됩니다.'],['오래된 장비도 처리할 수 있나요?','사양과 상태에 따라 매입 또는 수거 방식으로 안내합니다.'],['HDD 파기 요청도 가능한가요?','사업장 보안정책에 맞춰 저장장치 천공 파기 상담이 가능합니다.']],nearby:['seo-gu','sasang-gu','gangseo-gu']},
 'geumjeong-gu':{name:'금정구',neighborhoods:['장전동','부곡동','구서동','남산동','청룡동','노포동','금사동','회동동'],focus:'대학·연구시설·공장·사무실 전산장비 매입',intro:'금정구는 대학과 연구·교육시설, 구서·부곡 사무지역, 금사·회동 사업장이 함께 있습니다. 연구실 워크스테이션부터 사무용 PC, 공장 전산장비와 서버·네트워크 장비까지 종류에 맞춰 출장 상담합니다.',cases:[['대학·연구실 장비','연구용 PC, 워크스테이션, 서버와 고사양 부품을 별도로 확인합니다.'],['구서·부곡 사무실','사무용 데스크탑과 모니터, 노트북, NAS 등을 이전 일정에 맞춰 상담합니다.'],['금사·회동 사업장','공장 사무용 PC와 산업현장 네트워크 장비, 통신자재를 함께 확인합니다.'],['교육시설 장비교체','다수의 교육용 PC와 모니터를 일괄 견적하고 수거 일정을 조율합니다.']],faq:[['연구실 워크스테이션도 매입하나요?','CPU, GPU, 메모리 등 사양을 확인해 일반 PC와 구분해 상담합니다.'],['교육용 PC가 대량인데 방문 가능한가요?','수량이 많은 경우 방문견적과 일괄 수거 일정을 협의할 수 있습니다.'],['데이터 파기도 포함할 수 있나요?','요청 시 HDD 등 저장장치의 물리적 파기 방법을 상담합니다.']],nearby:['dongnae-gu','buk-gu','gijang-gun','yeonje-gu']},
 'gangseo-gu':{name:'강서구',neighborhoods:['명지동','신호동','녹산동','송정동','대저동','강동동','가락동','미음동'],focus:'녹산산단·명지·공장·물류 사업장 대량매입',intro:'강서구는 녹산산단과 미음산단, 신호·송정의 제조업 사업장, 명지 업무·상업지역이 함께 있는 곳입니다. 공장·물류센터·기업의 불용 PC와 서버, 네트워크 장비, 통신스크랩을 대량 수거 일정에 맞춰 상담합니다.',cases:[['녹산·미음 공장 전산장비','생산관리용 PC, 사무실 컴퓨터, 서버와 네트워크 스위치를 현장 단위로 확인합니다.'],['명지 기업·사무실','업무용 PC, 노트북, 모니터와 NAS 등 사무실 장비를 이전 일정에 맞춰 견적합니다.'],['신호·송정 제조업 장비','산업현장의 통신장비, UPS, 보드류와 불용 전산자재도 함께 상담합니다.'],['물류센터 대량수거','장비 수량과 파렛트·반출 동선을 확인해 수거 차량과 방문일정을 조율합니다.']],faq:[['녹산산단 공장도 출장매입 가능한가요?','강서구 산업단지와 사업장 출장매입을 상담합니다.'],['서버와 통신스크랩을 같이 견적할 수 있나요?','가능합니다. 품목별 사진과 수량을 전달하면 사전 상담이 수월합니다.'],['대량 장비는 어떻게 수거하나요?','현장 반출 조건과 적재량을 확인해 방문 차량과 일정을 협의합니다.']],nearby:['saha-gu','sasang-gu','buk-gu']},
 'yeonje-gu':{name:'연제구',neighborhoods:['연산동','거제동'],focus:'연산 업무지구·법인·사무실 폐컴퓨터 매입',intro:'연제구는 연산동 업무·상업지구와 거제동의 공공·법무·사무시설이 밀집해 있습니다. 법인 사무실의 PC 교체, 이전·폐업 과정에서 발생하는 데스크탑과 모니터, 서버·NAS·네트워크 장비를 출장매입합니다.',cases:[['연산동 법인 사무실','다수의 사무용 PC, 듀얼모니터, 노트북과 NAS를 부서별 또는 일괄로 확인합니다.'],['거제동 업무시설','사무실 이전 과정에서 발생한 PC와 네트워크 장비의 수거 일정을 협의합니다.'],['법무·전문서비스업','고객정보가 저장된 업무용 PC는 저장장치 처리 방법까지 함께 상담합니다.'],['서버·NAS 장비 교체','소규모 서버와 NAS, 스위치, UPS 등 사무실 전산장비를 한 번에 견적합니다.']],faq:[['연산동 사무실 컴퓨터 대량매입 가능한가요?','수량과 장비 사양을 먼저 확인한 뒤 방문견적을 협의합니다.'],['법인 PC의 HDD는 별도 파기할 수 있나요?','요청 시 저장장치 분리와 천공 파기 상담이 가능합니다.'],['NAS와 스위치도 함께 매입하나요?','NAS, 스위치, 라우터, UPS 등 네트워크 장비도 함께 상담합니다.']],nearby:['busanjin-gu','dongnae-gu','suyeong-gu','haeundae-gu']},
 'suyeong-gu':{name:'수영구',neighborhoods:['광안동','남천동','수영동','민락동','망미동'],focus:'상가·병원·숙박·소규모 사업장 출장매입',intro:'수영구는 광안리·민락 상권과 남천·수영의 병원·학원·사무실이 혼재한 지역입니다. 매장·숙박업 운영 PC부터 사무용 컴퓨터, 모니터, 네트워크 장비까지 소량·중량에 맞춰 출장 또는 택배매입을 안내합니다.',cases:[['광안·민락 상가 장비','매장 PC, POS 주변장비, 모니터와 공유기·스위치 등을 함께 확인합니다.'],['남천 병원·학원 PC','접수·업무·교육용 PC와 모니터, 네트워크 장비를 일괄 견적합니다.'],['숙박·서비스업 장비','관리용 PC와 프런트 장비, 네트워크 장비를 교체 일정에 맞춰 상담합니다.'],['망미 소규모 사업장','소량의 업무용 PC와 노트북은 품목에 따라 출장 또는 택배방식을 안내합니다.']],faq:[['광안리 상가 폐업 장비도 가능한가요?','매장 PC와 모니터, 네트워크 장비 등을 함께 상담할 수 있습니다.'],['소량 PC도 방문하나요?','품목과 수량, 위치에 따라 출장 또는 택배매입 중 적합한 방식을 안내합니다.'],['HDD 파기도 상담 가능한가요?','개인정보가 남은 저장장치는 요청 시 천공 파기 상담이 가능합니다.']],nearby:['nam-gu','haeundae-gu','yeonje-gu','busanjin-gu']},
 'sasang-gu':{name:'사상구',neighborhoods:['감전동','괘법동','덕포동','모라동','삼락동','엄궁동','주례동','학장동'],focus:'산업단지·공장·유통업 불용 전산장비 일괄매입',intro:'사상구는 감전·학장·엄궁의 공장·유통·산업시설과 괘법·주례의 상업·업무시설이 함께 분포합니다. 공장 사무실의 폐컴퓨터부터 서버, 네트워크 장비, 통신스크랩과 불용 전산자재까지 대량 출장매입에 적합한 지역입니다.',cases:[['감전·학장 공장 장비','생산관리 PC, 사무용 컴퓨터와 네트워크 장비를 공장별로 확인합니다.'],['엄궁 유통·물류업','사무실 PC와 서버, 스위치, 통신장비 등 물류 운영장비를 함께 상담합니다.'],['괘법·주례 사무실','업무용 PC와 모니터, 노트북, NAS를 이전 일정에 맞춰 수거합니다.'],['대량 불용자재','보드류, 케이블, 통신장비와 폐PC가 섞여 있는 경우 품목별 분류 후 상담합니다.']],faq:[['공장 PC와 통신장비를 함께 매입하나요?','가능합니다. 사진과 수량을 사전에 전달하면 현장 견적 준비가 수월합니다.'],['대량 수거 차량도 가능한가요?','물량과 반출 조건을 확인한 뒤 적절한 수거 일정을 협의합니다.'],['오래된 서버도 매입 대상인가요?','모델과 상태에 따라 매입 또는 수거 방법을 안내합니다.']],nearby:['buk-gu','saha-gu','gangseo-gu','busanjin-gu']},
 'gijang-gun':{name:'기장군',neighborhoods:['기장읍','정관읍','장안읍','일광읍','철마면'],focus:'산업단지·공장·사업장·상가 출장매입',intro:'기장군은 정관·장안 산업지역과 기장·일광의 상업·업무시설이 넓게 분포합니다. 거리와 물량을 고려해 공장·사업장의 폐컴퓨터, 서버·네트워크 장비, 통신불용품과 사무실 장비를 사전 상담 후 출장매입합니다.',cases:[['정관 사업장·공장','사무용 PC, 생산관리 컴퓨터, 서버와 네트워크 장비를 수량별로 확인합니다.'],['장안 산업지역','통신장비, UPS, 보드류와 불용 전산자재를 폐PC와 함께 상담합니다.'],['기장·일광 상가·사무실','매장·사무용 PC, 모니터와 노트북을 이전·폐업 일정에 맞춰 견적합니다.'],['원거리 대량수거','장비 수량이 많은 경우 사진·목록을 먼저 확인해 차량과 방문 일정을 효율적으로 조율합니다.']],faq:[['정관이나 장안도 출장 가능한가요?','기장군 전역은 물량과 품목을 사전 확인한 뒤 출장 일정을 협의합니다.'],['공장 서버와 PC를 함께 견적할 수 있나요?','가능합니다. 서버 모델과 PC 사양, 수량을 함께 알려주시면 좋습니다.'],['소량이면 어떻게 하나요?','거리와 품목에 따라 택배매입 등 다른 방법을 안내할 수 있습니다.']],nearby:['haeundae-gu','geumjeong-gu','dongnae-gu']}
};

const gyeongnam=[['changwon','창원시'],['gimhae','김해시'],['yangsan','양산시'],['jinju','진주시'],['geoje','거제시'],['tongyeong','통영시'],['sacheon','사천시'],['miryang','밀양시'],['geochang','거창군'],['hamyang','함양군'],['hapcheon','합천군'],['changnyeong','창녕군'],['goseong','고성군'],['namhae','남해군'],['hadong','하동군'],['sancheong','산청군'],['uiryeong','의령군']] as const;

export const dynamic='force-dynamic';
type Props={params:Promise<{region:string;slug?:string[]}>};

export async function generateMetadata({params}:Props):Promise<Metadata>{
 const {region,slug}=await params; const s=slug?.[0];
 if(region==='busan'&&s&&busanData[s]){const d=busanData[s]; return {title:`${d.name} 폐컴퓨터 매입｜부산 출장매입 | 올바른매입`,description:`부산 ${d.name} 폐컴퓨터 출장매입. ${d.focus}. 폐PC·모니터·서버·네트워크·불용 전산장비 매입과 HDD 천공 파기 상담.`,alternates:{canonical:`/buy/busan/${s}`}};}
 if(region==='busan') return {title:'부산 폐컴퓨터 출장매입｜16개 구·군 | 올바른매입',description:'부산 전 지역 폐컴퓨터·서버·네트워크·불용 전산장비 출장매입. 기업·사무실·공장·PC방 대량수거와 HDD 천공 파기 상담.'};
 if(region==='gyeongnam') return {title:'경남 폐컴퓨터 출장매입 | 올바른매입',description:'경남 지역 폐컴퓨터·서버·네트워크·불용 전산장비 출장매입 상담.'};
 return {};
}

function Header(){return <header className="siteHeader"><div className="container navWrap"><a href="/" className="brand"><span className="brandMark">↻</span><span>올바른<span className="brandBlue">매입</span></span></a><nav className="desktopNav"><a href="/">폐컴퓨터 매입</a><a href="/buy/busan">부산/경남 지역 출장매입</a><a href="/process">매입절차</a><a href="/request">수거신청서</a><a href="/customer/notice">고객센터</a></nav><a className="btn btnPrimary smallBtn" href="/request/visit">출장 견적문의</a></div></header>}

export default async function RegionalBuyPage({params}:Props){
 const {region,slug}=await params; const s=slug?.[0];
 if(region==='busan'){
  if(!s){const entries=Object.entries(busanData); return <main><Header/><section className="hero"><div className="container" style={{padding:'72px 0'}}><p className="sectionKicker">BUSAN ON-SITE BUYING</p><h1 style={{fontSize:50,margin:'8px 0 18px'}}>부산 폐컴퓨터 출장매입</h1><p className="heroDesc">부산 16개 구·군의 기업·사무실·공장·병원·학원·PC방에서 발생하는 폐컴퓨터와 서버·네트워크·불용 전산장비를 지역 특성에 맞춰 상담합니다.</p></div></section><section className="section"><div className="container"><div className="threeGrid">{entries.map(([slug,d])=><article className="categoryCard" key={slug}><h2>{d.name} 폐컴퓨터 매입</h2><p style={{color:'#667990',lineHeight:1.8}}>{d.focus}</p><a className="textLink" href={`/buy/busan/${slug}`}>지역 페이지 보기 →</a></article>)}</div></div></section></main>}
  const d=busanData[s]; if(!d)notFound();
  const imageBase=`/images/buy/busan/${s}`;
  const faq=d.faq;
  const jsonLd={'@context':'https://schema.org','@graph':[{'@type':'Service',name:`${d.name} 폐컴퓨터 출장매입`,areaServed:{'@type':'AdministrativeArea',name:`부산광역시 ${d.name}`},provider:{'@type':'LocalBusiness',name:'올바른매입'},serviceType:['폐컴퓨터 매입','서버 매입','네트워크 장비 매입','불용 전산장비 매입','HDD 천공 파기 상담']},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'홈',item:'/'},{'@type':'ListItem',position:2,name:'부산 폐컴퓨터 매입',item:'/buy/busan'},{'@type':'ListItem',position:3,name:`${d.name} 폐컴퓨터 매입`,item:`/buy/busan/${s}`}]},{'@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]};
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><Header/>
  <section className="hero"><div className="container" style={{padding:'72px 0 42px'}}><p className="sectionKicker">BUSAN LOCAL ON-SITE BUYING</p><h1 style={{fontSize:52,margin:'8px 0 18px'}}>{d.name} 폐컴퓨터 매입</h1><p className="heroDesc">{d.intro}</p><div className="heroActions"><a href="/request/visit" className="btn btnPrimary">출장매입 견적문의</a><a href="/request/pickup" className="btn btnGhost">수거 신청하기</a></div><p className="trustLine">{d.focus} · 대량 장비 일괄견적 · HDD 천공 파기 상담</p></div></section>
  <section className="section" style={{paddingTop:36}}><div className="container"><div style={{minHeight:360,borderRadius:20,overflow:'hidden',backgroundImage:`linear-gradient(90deg,rgba(6,26,51,.80),rgba(6,26,51,.22)),url('${imageBase}-hero.webp')`,backgroundSize:'cover',backgroundPosition:'center',display:'flex',alignItems:'end',padding:36,color:'#fff',backgroundColor:'#12345b'}}><div><h2 style={{fontSize:32,margin:'0 0 10px'}}>{d.name} 전 지역 출장매입</h2><p style={{margin:0,lineHeight:1.7}}>이미지 파일 <b>{s}-hero.webp</b>를 /public/images/buy/busan/ 폴더에 업로드하면 자동 표시됩니다.</p></div></div></div></section>
  <section className="section" style={{paddingTop:18}}><div className="container"><div className="sectionHead"><div><p className="sectionKicker">LOCAL COVERAGE</p><h2>{d.name} 주요 출장 가능지역</h2></div><p>사업장 위치와 장비 수량에 맞춰 방문 견적과 수거 일정을 협의합니다.</p></div><div style={{display:'flex',flexWrap:'wrap',gap:10}}>{d.neighborhoods.map(n=><span key={n} style={{padding:'10px 14px',border:'1px solid #d7e2ee',borderRadius:999,background:'#f8fbff',fontWeight:700,color:'#27415f'}}>{n}</span>)}</div></div></section>
  <section className="section" style={{background:'#f7f9fc'}}><div className="container"><div className="sectionHead"><div><p className="sectionKicker">LOCAL BUYING</p><h2>{d.name}에서 자주 발생하는 매입 유형</h2></div></div><div className="processDetailGrid">{d.cases.map(([t,c])=><div key={t}><strong>{t}</strong><p>{c}</p></div>)}</div></div></section>
  <section className="section"><div className="container"><div className="sectionHead"><div><p className="sectionKicker">BUYING ITEMS</p><h2>폐PC부터 서버·통신장비까지 함께 견적</h2></div></div><div className="threeGrid"><article className="categoryCard category1"><h2>폐컴퓨터·모니터</h2><ul><li>사무용 데스크탑</li><li>노트북·일체형 PC</li><li>LCD 모니터</li><li>PC방·사업장 장비</li></ul></article><article className="categoryCard category2"><h2>서버·네트워크</h2><ul><li>랙서버·워크스테이션</li><li>스위치·라우터</li><li>NAS·UPS</li><li>기업 전산장비</li></ul></article><article className="categoryCard category3"><h2>통신스크랩·불용자재</h2><ul><li>메인보드·보드류</li><li>통신장비</li><li>케이블·전산자재</li><li>사업장 불용품</li></ul></article></div></div></section>
  <section className="securitySection"><div className="container securityGrid"><div><p className="sectionKicker light">DATA SECURITY</p><h2>장비는 매입하고<br/><span>중요 데이터는 확실하게 처리</span></h2><p>{d.name}의 기업·병원·학원·사무실에서 사용하던 폐컴퓨터에는 개인정보와 내부자료가 남아 있을 수 있습니다. 요청 시 HDD 등 저장장치를 분리해 전용 천공 장비로 물리적 파기하는 방법을 상담합니다.</p><a href="/request/visit" className="btn btnGreen">HDD 파기 포함 견적문의</a></div><div className="securitySteps"><div className="securityStep"><span>01</span><div className="driveIcon">HDD</div><strong>저장장치 확인</strong></div><div className="stepArrow">→</div><div className="securityStep"><span>02</span><div className="drillIcon">●</div><strong>천공 처리</strong></div><div className="stepArrow">→</div><div className="securityStep"><span>03</span><div className="driveIcon broken">×</div><strong>폐기·처리</strong></div></div></div></section>
  <section className="section"><div className="container"><div style={{minHeight:320,borderRadius:18,overflow:'hidden',backgroundImage:`linear-gradient(0deg,rgba(7,29,58,.72),rgba(7,29,58,.10)),url('${imageBase}-content.webp')`,backgroundSize:'cover',backgroundPosition:'center',display:'flex',alignItems:'end',padding:32,color:'#fff',backgroundColor:'#34506f'}}><div><h2 style={{margin:'0 0 8px',fontSize:28}}>{d.name} 현장 수거·전산장비 이미지</h2><p style={{margin:0,lineHeight:1.7}}>파일명 <b>{s}-content.webp</b>를 같은 부산 이미지 폴더에 올리면 자동 표시됩니다.</p></div></div></div></section>
  <section className="section" style={{background:'#f7fbff'}}><div className="container"><div className="centerHead"><p className="sectionKicker">PROCESS</p><h2>{d.name} 출장매입 진행 순서</h2></div><div className="processTrust"><div><b>1</b><strong>견적문의</strong><span>품목·수량·사진 전달</span></div><div><b>2</b><strong>사전견적</strong><span>장비 기준 확인</span></div><div><b>3</b><strong>방문일정</strong><span>날짜·장소 협의</span></div><div><b>4</b><strong>수거·결제</strong><span>현장 확인 후 처리</span></div></div></div></section>
  <section className="section"><div className="container"><div className="sectionHead"><div><p className="sectionKicker">FAQ</p><h2>{d.name} 폐컴퓨터 매입 자주 묻는 질문</h2></div></div><div style={{display:'grid',gap:14}}>{faq.map(([q,a])=><details key={q} style={{border:'1px solid #dce6f0',borderRadius:12,padding:'18px 20px',background:'#fff'}}><summary style={{fontWeight:800,cursor:'pointer'}}>{q}</summary><p style={{color:'#62758d',lineHeight:1.8,margin:'14px 0 0'}}>{a}</p></details>)}</div></div></section>
  <section className="section" style={{paddingTop:20}}><div className="container"><div className="sectionHead"><div><p className="sectionKicker">NEARBY AREA</p><h2>부산 인접 지역 출장매입</h2></div></div><div style={{display:'flex',flexWrap:'wrap',gap:12}}>{d.nearby.map(n=><a key={n} className="btn btnGhost" href={`/buy/busan/${n}`}>{busanData[n]?.name||'부산'} 폐컴퓨터 매입</a>)}<a className="btn btnGhost" href="/buy/busan">부산 전체지역 보기</a></div></div></section>
  <section className="darkCta"><div className="container ctaWrap"><div><h2>{d.name} 출장매입이 필요하신가요?</h2><p>품목과 수량, 위치를 알려주시면 현장에 맞는 매입 방법을 안내해드립니다.</p></div><a href="/request/visit" className="btn btnYellow">방문견적 의뢰서</a></div></section>
  </main>
 }
 if(region==='gyeongnam'){
  const area=s?gyeongnam.find(x=>x[0]===s):undefined; if(s&&!area)notFound(); const name=area?.[1];
  return <main><Header/><section className="hero"><div className="container" style={{padding:'72px 0'}}><p className="sectionKicker">GYEONGNAM ON-SITE BUYING</p><h1 style={{fontSize:48,margin:'8px 0 18px'}}>{name?`${name} 폐컴퓨터 매입`:'경남 폐컴퓨터 출장매입'}</h1><p className="heroDesc">{name?`${name}의 기업·사무실·공장·사업장에서 발생하는 폐컴퓨터, 서버·네트워크 장비와 불용 전산장비 출장매입을 상담합니다.`:'경남 주요 시·군의 폐컴퓨터와 서버·네트워크·불용 전산장비 출장매입을 상담합니다.'}</p></div></section><section className="section"><div className="container">{!name?<div className="threeGrid">{gyeongnam.map(([slug,n])=><article className="categoryCard" key={slug}><h2>{n} 폐컴퓨터 매입</h2><p style={{color:'#667990',lineHeight:1.8}}>폐컴퓨터·서버·네트워크·불용 전산장비 출장매입 상담</p><a className="textLink" href={`/buy/gyeongnam/${slug}`}>지역 페이지 보기 →</a></article>)}</div>:<div className="processDetailGrid"><div><strong>폐컴퓨터·모니터</strong><p>사무용 PC, 노트북, 모니터와 사업장 불용 장비를 상담합니다.</p></div><div><strong>서버·네트워크</strong><p>랙서버, 워크스테이션, 스위치, 라우터, UPS 등도 함께 확인합니다.</p></div><div><strong>출장매입</strong><p>수량이 많은 경우 현장 상황에 맞춰 방문 일정을 협의합니다.</p></div><div><strong>HDD 데이터 파기</strong><p>요청 시 저장장치 물리적 천공 파기 상담이 가능합니다.</p></div></div>}</div></section></main>
 }
 notFound();
}
