const methods = [
  { no:'01', title:'출장매입', note:'수량이 많은 경우 출장 방문하여 매입', steps:['견적문의','견적제공','계약 및 날짜협의','방문수거','결제'] },
  { no:'02', title:'현장방문매입', note:'대량의 물품 확인이 어려울 경우 진행 · 출장비 무료', steps:['견적문의','날짜협의','현장방문','견적제공','계약 및 날짜협의','방문수거','결제'] },
  { no:'03', title:'택배매입', note:'소량의 경우 택배로 간편하게 매입', steps:['견적문의','견적제공','택배 발송','물품확인','결제'] },
  { no:'04', title:'직접방문', note:'소량·대량 물품을 직접 방문하여 진행 · 현장에서 결제', steps:['견적문의','직접방문','물품확인','결제'] },
];
const icons=['✎','▤','▣','⌂','▱','▦','▢'];
export default function ProcessPage(){return <main>
<header className="siteHeader"><div className="container navWrap"><a href="/" className="brand"><span className="brandMark">↻</span><span>올바른<span className="brandBlue">매입</span></span></a><nav className="desktopNav"><a href="/#category">폐컴퓨터 매입</a><a href="/#price">매입단가</a><a href="/process">매입절차</a><a href="/#security">데이터파기</a></nav><a href="/#quote" className="btn btnPrimary smallBtn">빠른 견적 문의</a></div></header>
<section className="processPage"><div className="container"><div className="processHero"><p className="sectionKicker">PROCESS</p><h1>올바른<span>매입</span> 절차 안내</h1><p>물량과 상황에 맞는 4가지 매입 방식으로 편리하게 진행하세요.</p></div><div className="processRows">{methods.map((m)=><article className="processRow" key={m.no}><div className="processIntro"><strong className="processNo">{m.no}<i>.</i></strong><div><h2>{m.title}</h2><p>{m.note}</p></div></div><div className="horizontalSteps">{m.steps.map((s,i)=><div className="horizontalStepWrap" key={s+i}><div className="horizontalStep"><span>{icons[i%icons.length]}</span><strong>{s}</strong></div>{i<m.steps.length-1&&<b className="horizontalArrow">›</b>}</div>)}</div></article>)}</div><div className="processTrust"><div><b>◇</b><strong>모든 정보 보안</strong><span>안전한 정보 보호를 우선합니다.</span></div><div><b>◷</b><strong>신속한 처리</strong><span>빠르고 정확한 매입을 진행합니다.</span></div><div><b>₩</b><strong>정확한 시세</strong><span>실시간 시세를 기준으로 견적합니다.</span></div><div><b>♧</b><strong>1:1 고객상담</strong><span>매입 절차를 친절하게 안내합니다.</span></div></div><div className="processDetail"><h2>어떤 매입 방법을 선택해야 할까요?</h2><div className="processDetailGrid"><div><strong>대량 장비라면 출장매입</strong><p>사무실, 기업, PC방처럼 수량이 많거나 운반이 어려운 경우 담당자가 일정과 장소를 협의한 뒤 방문 수거합니다.</p></div><div><strong>현장에서 먼저 확인이 필요하다면</strong><p>정확한 품목이나 수량 확인이 어려운 대량 물량은 현장을 방문해 상태와 구성을 확인한 후 견적을 안내합니다.</p></div><div><strong>소량이라면 택배매입</strong><p>컴퓨터나 부품 등 소량 물품은 사전 견적을 확인한 뒤 택배로 발송하고, 도착 후 검수하여 최종 결제를 진행합니다.</p></div><div><strong>빠르게 처리하려면 직접방문</strong><p>직접 방문이 가능한 경우 현장에서 물품을 확인하고 최종 매입금액을 확인한 뒤 결제까지 진행할 수 있습니다.</p></div></div></div><div className="processNotice"><div><p className="sectionKicker light">DATA SECURITY</p><h2>저장장치 데이터 파기도 함께 상담하세요.</h2><p>폐컴퓨터에 포함된 HDD 등 중요 저장장치는 요청 시 전용 천공 장비를 이용한 물리적 파기 절차를 상담할 수 있습니다.</p></div><a href="/#quote" className="btn btnGreen">매입 견적 문의</a></div></div></section>
<footer className="footer"><div className="container footerGrid"><div className="brand footerBrand"><span className="brandMark">↻</span><span>올바른매입</span></div><div><strong>매입안내</strong><p>출장 · 현장방문 · 택배 · 직접방문</p></div><div><strong>취급품목</strong><p>폐컴퓨터 · 서버 · 네트워크 · 통신스크랩</p></div><div><strong>데이터 보안</strong><p>저장장치 물리적 천공 파기 상담</p></div></div></footer></main>