'use client';
import { FormEvent,useState } from 'react';
import { useRouter } from 'next/navigation';

export default function NoticeWriteForm(){
 const [status,setStatus]=useState(''); const [sending,setSending]=useState(false); const router=useRouter();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSending(true);setStatus('');const fd=new FormData(e.currentTarget);try{const res=await fetch('/api/admin/notices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:fd.get('title'),content:fd.get('content')})});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.message||'공지 등록 중 오류가 발생했습니다.');setStatus('공지사항이 등록되었습니다.');setTimeout(()=>{router.push('/customer/notice');router.refresh();},700);}catch(err){setStatus(err instanceof Error?err.message:'공지 등록 중 오류가 발생했습니다.');}finally{setSending(false);}}
 return <form onSubmit={submit} style={{maxWidth:900,margin:'0 auto',borderTop:'2px solid #24364c'}}><label style={{display:'grid',gridTemplateColumns:'140px 1fr',borderBottom:'1px solid #e2e7ed'}}><span style={{padding:18,background:'#f7f9fb',fontWeight:800}}>제목 *</span><div style={{padding:10}}><input name="title" required maxLength={160} style={{width:'100%',height:46,border:'1px solid #cfd8e3',borderRadius:6,padding:'0 12px'}}/></div></label><label style={{display:'grid',gridTemplateColumns:'140px 1fr',borderBottom:'1px solid #e2e7ed'}}><span style={{padding:18,background:'#f7f9fb',fontWeight:800}}>내용 *</span><div style={{padding:10}}><textarea name="content" required maxLength={10000} style={{width:'100%',minHeight:360,border:'1px solid #cfd8e3',borderRadius:6,padding:14,resize:'vertical'}}/></div></label><div style={{display:'flex',justifyContent:'center',gap:10,marginTop:24}}><button disabled={sending} style={{padding:'13px 28px',border:0,borderRadius:7,background:'#172d49',color:'#fff',fontWeight:800}}>{sending?'등록 중...':'공지 등록'}</button><a href="/customer/notice" style={{padding:'13px 28px',borderRadius:7,background:'#eef2f6',fontWeight:800}}>취소</a></div>{status&&<p style={{textAlign:'center',fontWeight:800,marginTop:16}}>{status}</p>}</form>;
}
